function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = -100000; // obj_global
	global.__objectDepths[1] = 0; // obj_stage_control
	global.__objectDepths[2] = 0; // obj_collision_solid
	global.__objectDepths[3] = 0; // obj_collision_ice
	global.__objectDepths[4] = 0; // obj_collision_solid_no_wall
	global.__objectDepths[5] = 0; // obj_collision_semisolid
	global.__objectDepths[6] = 0; // obj_collision_ladder
	global.__objectDepths[7] = 0; // obj_collision_slope
	global.__objectDepths[8] = 0; // obj_collision_slope_right
	global.__objectDepths[9] = 0; // obj_collision_slope_left
	global.__objectDepths[10] = 0; // obj_collision_water
	global.__objectDepths[11] = 0; // obj_collision_spike
	global.__objectDepths[12] = 0; // prt_player
	global.__objectDepths[13] = -1; // obj_x
	global.__objectDepths[14] = -1; // obj_zero
	global.__objectDepths[15] = 0; // obj_camera
	global.__objectDepths[16] = 0; // obj_dash_trail
	global.__objectDepths[17] = 0; // prt_player_projectile
	global.__objectDepths[18] = -2; // obj_effect_buster
	global.__objectDepths[19] = -2; // obj_effect_buster_half_charged
	global.__objectDepths[20] = -2; // obj_effect_buster_charged
	global.__objectDepths[21] = -3; // obj_weapon_buster
	global.__objectDepths[22] = -3; // obj_weapon_buster_half_charged
	global.__objectDepths[23] = -3; // obj_weapon_buster_charged
	global.__objectDepths[24] = -12; // obj_effect_buster_destroy
	global.__objectDepths[25] = -2; // obj_effect_buster_charged_destroy
	global.__objectDepths[26] = -12; // obj_effect_weapon_reflect
	global.__objectDepths[27] = -3; // obj_player_saber_mask
	global.__objectDepths[28] = -12; // obj_effect_saber_contact
	global.__objectDepths[29] = -3; // obj_weapon_test1
	global.__objectDepths[30] = -3; // obj_weapon_test1_giga
	global.__objectDepths[31] = -3; // obj_weapon_test2
	global.__objectDepths[32] = 0; // obj_player_die
	global.__objectDepths[33] = 0; // obj_death_orb
	global.__objectDepths[34] = -1000; // obj_hud
	global.__objectDepths[35] = -10000; // obj_debug_hud
	global.__objectDepths[36] = 100000; // obj_parallax
	global.__objectDepths[37] = 0; // obj_player_teleport_out
	global.__objectDepths[38] = 0; // prt_enemy
	global.__objectDepths[39] = 0; // prt_harmful_projectile
	global.__objectDepths[40] = 0; // obj_test_enemy_1
	global.__objectDepths[41] = 0; // obj_test_enemy_2
	global.__objectDepths[42] = 0; // obj_test_enemy_3
	global.__objectDepths[43] = 0; // obj_test_enemy_4
	global.__objectDepths[44] = -3; // obj_test_projectile_1
	global.__objectDepths[45] = -3; // obj_test_projectile_2
	global.__objectDepths[46] = -1000; // obj_boss_control
	global.__objectDepths[47] = 0; // prt_boss
	global.__objectDepths[48] = 0; // obj_template_boss
	global.__objectDepths[49] = -3; // obj_template_boss_projectile
	global.__objectDepths[50] = -100; // obj_boss_explosion_fade
	global.__objectDepths[51] = 0; // obj_boss_clear
	global.__objectDepths[52] = 0; // obj_dash_dust
	global.__objectDepths[53] = -1; // obj_dash_boost
	global.__objectDepths[54] = -10; // obj_wall_dust
	global.__objectDepths[55] = -1; // obj_wall_kick_spark
	global.__objectDepths[56] = 1; // obj_explosion
	global.__objectDepths[57] = 0; // prt_item
	global.__objectDepths[58] = 0; // obj_item_life
	global.__objectDepths[59] = 0; // obj_item_health_energy
	global.__objectDepths[60] = 0; // obj_item_health_energy_small
	global.__objectDepths[61] = 0; // obj_item_weapon_energy_small
	global.__objectDepths[62] = 0; // obj_item_weapon_energy
	global.__objectDepths[63] = 0; // obj_item_heart_tank
	global.__objectDepths[64] = 0; // obj_item_sub_tank
	global.__objectDepths[65] = 0; // obj_item_weapons_tank
	global.__objectDepths[66] = 0; // obj_item_ex_tank
	global.__objectDepths[67] = 0; // prt_boss_door
	global.__objectDepths[68] = 0; // obj_boss_door_h
	global.__objectDepths[69] = 0; // obj_boss_door_v
	global.__objectDepths[70] = 0; // prt_moving_solid
	global.__objectDepths[71] = 0; // obj_mobile_wall
	global.__objectDepths[72] = 0; // obj_test_moving_ground
	global.__objectDepths[73] = 0; // obj_test_falling_ground
	global.__objectDepths[74] = 0; // obj_lightcapsule
	global.__objectDepths[75] = 0; // prt_breakable_solid
	global.__objectDepths[76] = 0; // obj_break_box_test_1
	global.__objectDepths[77] = 0; // obj_break_box_test_2
	global.__objectDepths[78] = 0; // obj_break_box_test_3
	global.__objectDepths[79] = 0; // obj_rematch_control
	global.__objectDepths[80] = 0; // obj_teleporter_rematch
	global.__objectDepths[81] = 0; // obj_teleporter_rematch_last_spawn
	global.__objectDepths[82] = 0; // obj_trigger_camera_changer
	global.__objectDepths[83] = 0; // obj_trigger_direction
	global.__objectDepths[84] = 0; // obj_trigger_stage_end
	global.__objectDepths[85] = 0; // obj_trigger_checkpoint
	global.__objectDepths[86] = 0; // obj_debug_menu
	global.__objectDepths[87] = 0; // obj_title_screen
	global.__objectDepths[88] = 0; // obj_option_menu
	global.__objectDepths[89] = 0; // obj_key_config
	global.__objectDepths[90] = 0; // obj_character_select
	global.__objectDepths[91] = -10000; // obj_pause_menu
	global.__objectDepths[92] = 0; // obj_stage_select
	global.__objectDepths[93] = 0; // obj_capcom_logo
	global.__objectDepths[94] = 0; // obj_weapon_get
	global.__objectDepths[95] = 0; // obj_boss_intro
	global.__objectDepths[96] = 0; // obj_data_select
	global.__objectDepths[97] = 0; // obj_save_game
	global.__objectDepths[98] = -100000; // obj_fade_in
	global.__objectDepths[99] = -100000; // obj_fade_out
	global.__objectDepths[100] = -10000; // obj_dialogue
	global.__objectDepths[101] = -10000; // obj_ready
	global.__objectDepths[102] = -100; // obj_warning


	global.__objectNames[0] = "obj_global";
	global.__objectNames[1] = "obj_stage_control";
	global.__objectNames[2] = "obj_collision_solid";
	global.__objectNames[3] = "obj_collision_ice";
	global.__objectNames[4] = "obj_collision_solid_no_wall";
	global.__objectNames[5] = "obj_collision_semisolid";
	global.__objectNames[6] = "obj_collision_ladder";
	global.__objectNames[7] = "obj_collision_slope";
	global.__objectNames[8] = "obj_collision_slope_right";
	global.__objectNames[9] = "obj_collision_slope_left";
	global.__objectNames[10] = "obj_collision_water";
	global.__objectNames[11] = "obj_collision_spike";
	global.__objectNames[12] = "prt_player";
	global.__objectNames[13] = "obj_x";
	global.__objectNames[14] = "obj_zero";
	global.__objectNames[15] = "obj_camera";
	global.__objectNames[16] = "obj_dash_trail";
	global.__objectNames[17] = "prt_player_projectile";
	global.__objectNames[18] = "obj_effect_buster";
	global.__objectNames[19] = "obj_effect_buster_half_charged";
	global.__objectNames[20] = "obj_effect_buster_charged";
	global.__objectNames[21] = "obj_weapon_buster";
	global.__objectNames[22] = "obj_weapon_buster_half_charged";
	global.__objectNames[23] = "obj_weapon_buster_charged";
	global.__objectNames[24] = "obj_effect_buster_destroy";
	global.__objectNames[25] = "obj_effect_buster_charged_destroy";
	global.__objectNames[26] = "obj_effect_weapon_reflect";
	global.__objectNames[27] = "obj_player_saber_mask";
	global.__objectNames[28] = "obj_effect_saber_contact";
	global.__objectNames[29] = "obj_weapon_test1";
	global.__objectNames[30] = "obj_weapon_test1_giga";
	global.__objectNames[31] = "obj_weapon_test2";
	global.__objectNames[32] = "obj_player_die";
	global.__objectNames[33] = "obj_death_orb";
	global.__objectNames[34] = "obj_hud";
	global.__objectNames[35] = "obj_debug_hud";
	global.__objectNames[36] = "obj_parallax";
	global.__objectNames[37] = "obj_player_teleport_out";
	global.__objectNames[38] = "prt_enemy";
	global.__objectNames[39] = "prt_harmful_projectile";
	global.__objectNames[40] = "obj_test_enemy_1";
	global.__objectNames[41] = "obj_test_enemy_2";
	global.__objectNames[42] = "obj_test_enemy_3";
	global.__objectNames[43] = "obj_test_enemy_4";
	global.__objectNames[44] = "obj_test_projectile_1";
	global.__objectNames[45] = "obj_test_projectile_2";
	global.__objectNames[46] = "obj_boss_control";
	global.__objectNames[47] = "prt_boss";
	global.__objectNames[48] = "obj_template_boss";
	global.__objectNames[49] = "obj_template_boss_projectile";
	global.__objectNames[50] = "obj_boss_explosion_fade";
	global.__objectNames[51] = "obj_boss_clear";
	global.__objectNames[52] = "obj_dash_dust";
	global.__objectNames[53] = "obj_dash_boost";
	global.__objectNames[54] = "obj_wall_dust";
	global.__objectNames[55] = "obj_wall_kick_spark";
	global.__objectNames[56] = "obj_explosion";
	global.__objectNames[57] = "prt_item";
	global.__objectNames[58] = "obj_item_life";
	global.__objectNames[59] = "obj_item_health_energy";
	global.__objectNames[60] = "obj_item_health_energy_small";
	global.__objectNames[61] = "obj_item_weapon_energy_small";
	global.__objectNames[62] = "obj_item_weapon_energy";
	global.__objectNames[63] = "obj_item_heart_tank";
	global.__objectNames[64] = "obj_item_sub_tank";
	global.__objectNames[65] = "obj_item_weapons_tank";
	global.__objectNames[66] = "obj_item_ex_tank";
	global.__objectNames[67] = "prt_boss_door";
	global.__objectNames[68] = "obj_boss_door_h";
	global.__objectNames[69] = "obj_boss_door_v";
	global.__objectNames[70] = "prt_moving_solid";
	global.__objectNames[71] = "obj_mobile_wall";
	global.__objectNames[72] = "obj_test_moving_ground";
	global.__objectNames[73] = "obj_test_falling_ground";
	global.__objectNames[74] = "obj_lightcapsule";
	global.__objectNames[75] = "prt_breakable_solid";
	global.__objectNames[76] = "obj_break_box_test_1";
	global.__objectNames[77] = "obj_break_box_test_2";
	global.__objectNames[78] = "obj_break_box_test_3";
	global.__objectNames[79] = "obj_rematch_control";
	global.__objectNames[80] = "obj_teleporter_rematch";
	global.__objectNames[81] = "obj_teleporter_rematch_last_spawn";
	global.__objectNames[82] = "obj_trigger_camera_changer";
	global.__objectNames[83] = "obj_trigger_direction";
	global.__objectNames[84] = "obj_trigger_stage_end";
	global.__objectNames[85] = "obj_trigger_checkpoint";
	global.__objectNames[86] = "obj_debug_menu";
	global.__objectNames[87] = "obj_title_screen";
	global.__objectNames[88] = "obj_option_menu";
	global.__objectNames[89] = "obj_key_config";
	global.__objectNames[90] = "obj_character_select";
	global.__objectNames[91] = "obj_pause_menu";
	global.__objectNames[92] = "obj_stage_select";
	global.__objectNames[93] = "obj_capcom_logo";
	global.__objectNames[94] = "obj_weapon_get";
	global.__objectNames[95] = "obj_boss_intro";
	global.__objectNames[96] = "obj_data_select";
	global.__objectNames[97] = "obj_save_game";
	global.__objectNames[98] = "obj_fade_in";
	global.__objectNames[99] = "obj_fade_out";
	global.__objectNames[100] = "obj_dialogue";
	global.__objectNames[101] = "obj_ready";
	global.__objectNames[102] = "obj_warning";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
